export const GENDER_PREFS = 'GENDER_PREFS';
export const  OTHER_USER_GENDER_PREFS =  'OTHER_USER_GENDER_PREFS';
export const AGE_RANGE_PREFS = 'AGE_RANGE_PREFS';
export const DISTANCE_PREFS = 'DISTANCE_PREFS';
export const LOCATION_PREFS =  'LOCATION_PREFS';